In [ ]:
# TOKENIZATION 

In [2]:
from transformers import AutoTokenizer
from transformers import TFAutoModel
from transformers import TFAutoModelForSequenceClassification

In [3]:
checkpoint = 'distilbert-base-uncased-finetuned-sst-2-english'
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

text = [
    'this is a simple text', 
    'i ate short text'
]

In [37]:
input = tokenizer(text , padding=True, truncation=True , return_tensors='tf')
input

{'input_ids': <tf.Tensor: shape=(2, 7), dtype=int32, numpy=
array([[ 101, 2023, 2003, 1037, 3722, 3793,  102],
       [ 101, 1045, 8823, 2460, 3793,  102,    0]])>, 'attention_mask': <tf.Tensor: shape=(2, 7), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 0]])>}

In [10]:
input.keys()

dict_keys(['input_ids', 'attention_mask'])

In [11]:
input['input_ids']

<tf.Tensor: shape=(2, 7), dtype=int32, numpy=
array([[ 101, 2023, 2003, 1037, 3722, 3793,  102],
       [ 101, 1045, 2293, 2460, 3793,  102,    0]])>

In [12]:
input['attention_mask']

<tf.Tensor: shape=(2, 7), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 0]])>

In [20]:
model = TFAutoModel.from_pretrained('distilbert-base-uncased-finetuned-sst-2-english')
output = model(input)

Downloading:   0%|          | 0.00/256M [00:00<?, ?B/s]

Some layers from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing TFDistilBertModel: ['pre_classifier', 'classifier', 'dropout_19']
- This IS expected if you are initializing TFDistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFDistilBertModel were initialized from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertModel for predictions without further training.


In [23]:
output['last_hidden_state']

<tf.Tensor: shape=(2, 7, 768), dtype=float32, numpy=
array([[[ 0.3320293 ,  0.02742751,  0.18346703, ...,  0.31159946,
          0.6723575 ,  0.36877427],
        [ 0.4239502 ,  0.27092987, -0.07830648, ...,  0.08568719,
          0.5814348 ,  0.5713896 ],
        [ 0.29482278,  0.13571008,  0.04054649, ...,  0.16526826,
          0.52327955,  0.6798635 ],
        ...,
        [ 0.43496478,  0.14738175,  0.05489651, ...,  0.2700857 ,
          0.4811685 ,  0.47562525],
        [ 0.43679562,  0.20165877,  0.11719923, ...,  0.36819005,
          0.4024661 ,  0.4030651 ],
        [ 0.94820166,  0.05986686,  0.5224403 , ...,  0.7581328 ,
          0.16098009, -0.30662575]],

       [[ 0.2352387 , -0.15724163,  0.10453077, ...,  0.287233  ,
          0.9235809 , -0.16500083],
        [ 0.672294  ,  0.09057958, -0.20700504, ...,  0.25807652,
          0.961981  , -0.16170302],
        [ 0.6843438 ,  0.34063095,  0.50549793, ...,  0.14057136,
          0.7961355 , -0.04010963],
        ...,
 

In [25]:

model2 = TFAutoModelForSequenceClassification.from_pretrained('distilbert-base-uncased-finetuned-sst-2-english')

Some layers from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing TFDistilBertForSequenceClassification: ['dropout_19']
- This IS expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some layers of TFDistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english and are newly initialized: ['dropout_38']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [38]:
output2 = model2(input)

In [39]:
output2['logits']

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-3.1598666,  3.2557592],
       [ 2.7002509, -2.3572714]], dtype=float32)>

In [47]:
import tensorflow as tf

predict = tf.math.softmax(output2.logits , axis=1)
predict

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.00163312, 0.9983669 ],
       [0.993679  , 0.00632109]], dtype=float32)>

In [45]:
model2.config.id2label

{0: 'NEGATIVE', 1: 'POSITIVE'}

In [4]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')

text = [
    'this is a simple text', 
    'i ate short text'
]


input = tokenizer(text, padding=True, truncation=True, return_tensors='tf')

{'input_ids': <tf.Tensor: shape=(2, 7), dtype=int32, numpy=
array([[ 101, 2023, 2003, 1037, 3722, 3793,  102],
       [ 101, 1045, 8823, 2460, 3793,  102,    0]])>, 'token_type_ids': <tf.Tensor: shape=(2, 7), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])>, 'attention_mask': <tf.Tensor: shape=(2, 7), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 0]])>}

In [49]:
tokens = tokenizer('this is a simple texting')
tokens

{'input_ids': [101, 2023, 2003, 1037, 3722, 3793, 2075, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1]}

In [18]:
input_ids = tokenizer.convert_tokens_to_ids(tokens)
input_ids

[2023, 2003, 1037, 3722, 3793, 2075]

In [19]:
 model_token = tokenizer.prepare_for_model(input_ids)
model_token

{'input_ids': [101, 2023, 2003, 1037, 3722, 3793, 2075, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1]}

In [20]:
tokenizer.decode(model_token['input_ids'])

'[CLS] this is a simple texting [SEP]'

In [23]:
# batching muultiple tex together 

tokens = [tokenizer.tokenize(t) for t in text]
ids = [tokenizer.convert_tokens_to_ids(tok) for tok in tokens]
ids

[[2023, 2003, 1037, 3722, 3793], [1045, 8823, 2460, 3793]]

In [34]:
id1 = tf.constant([ids[0]])
id1

<tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[2023, 2003, 1037, 3722, 3793]])>

In [45]:
id2 = tf.constant([ids[1]])
id2
# id2(tokenizer.pad_token_id) * 4

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[1045, 8823, 2460, 3793]])>

In [43]:
import tensorflow as tf 
tokenizer.pad_token_id
# input_ids = tf.constant([ids])

0