In [1]:
doc = '''

{"intents": [
        {"tag": "greeting",
         "patterns": ["Hi", "How are you", "Is anyone there?", "Hello", "Good day"],
         "responses": ["Hello, thanks for visiting", "Good to see you again", "Hi there, how can I help?"],
         "context_set": ""
        },
        {"tag": "goodbye",
         "patterns": ["Bye", "See you later", "Goodbye"],
         "responses": ["See you later, thanks for visiting", "Have a nice day", "Bye! Come back again soon."]
        },
        {"tag": "thanks",
         "patterns": ["Thanks", "Thank you", "That's helpful"],
         "responses": ["Happy to help!", "Any time!", "My pleasure"]
        },
        {"tag": "hours",
         "patterns": ["What hours are you open?", "What are your hours?", "When are you open?" ],
         "responses": ["We're open every day 9am-9pm", "Our hours are 9am-9pm every day"]
        },
        {"tag": "payments",
         "patterns": ["Do you take credit cards?", "Do you accept Mastercard?", "Are you cash only?" ],
         "responses": ["We accept VISA, Mastercard and AMEX", "We accept most major credit cards"]
        },
        {"tag": "opentoday",
         "patterns": ["Are you open today?", "When do you open today?", "What are your hours today?"],
         "responses": ["We're open every day from 9am-9pm", "Our hours are 9am-9pm every day"]
        }
   ]
}

'''

In [2]:
import json
from nltk.stem import PorterStemmer
import pandas as pd 

In [3]:
jdata = json.loads(doc)
jdata

{'intents': [{'tag': 'greeting',
   'patterns': ['Hi', 'How are you', 'Is anyone there?', 'Hello', 'Good day'],
   'responses': ['Hello, thanks for visiting',
    'Good to see you again',
    'Hi there, how can I help?'],
   'context_set': ''},
  {'tag': 'goodbye',
   'patterns': ['Bye', 'See you later', 'Goodbye'],
   'responses': ['See you later, thanks for visiting',
    'Have a nice day',
    'Bye! Come back again soon.']},
  {'tag': 'thanks',
   'patterns': ['Thanks', 'Thank you', "That's helpful"],
   'responses': ['Happy to help!', 'Any time!', 'My pleasure']},
  {'tag': 'hours',
   'patterns': ['What hours are you open?',
    'What are your hours?',
    'When are you open?'],
   'responses': ["We're open every day 9am-9pm",
    'Our hours are 9am-9pm every day']},
  {'tag': 'payments',
   'patterns': ['Do you take credit cards?',
    'Do you accept Mastercard?',
    'Are you cash only?'],
   'responses': ['We accept VISA, Mastercard and AMEX',
    'We accept most major credit c

In [4]:
jdata.keys()

dict_keys(['intents'])

In [5]:
data = jdata['intents']
data

[{'tag': 'greeting',
  'patterns': ['Hi', 'How are you', 'Is anyone there?', 'Hello', 'Good day'],
  'responses': ['Hello, thanks for visiting',
   'Good to see you again',
   'Hi there, how can I help?'],
  'context_set': ''},
 {'tag': 'goodbye',
  'patterns': ['Bye', 'See you later', 'Goodbye'],
  'responses': ['See you later, thanks for visiting',
   'Have a nice day',
   'Bye! Come back again soon.']},
 {'tag': 'thanks',
  'patterns': ['Thanks', 'Thank you', "That's helpful"],
  'responses': ['Happy to help!', 'Any time!', 'My pleasure']},
 {'tag': 'hours',
  'patterns': ['What hours are you open?',
   'What are your hours?',
   'When are you open?'],
  'responses': ["We're open every day 9am-9pm",
   'Our hours are 9am-9pm every day']},
 {'tag': 'payments',
  'patterns': ['Do you take credit cards?',
   'Do you accept Mastercard?',
   'Are you cash only?'],
  'responses': ['We accept VISA, Mastercard and AMEX',
   'We accept most major credit cards']},
 {'tag': 'opentoday',
  'pat

In [6]:
data_diction = {
    'tag':[],
 'patterns':[], 
 'responses':[]
}


# go through the dictionary
for datum in data:
    # loop throup patterns
    for pattern in datum['patterns']:
        data_diction['patterns'].append(pattern)
        data_diction['tag'].append(datum['tag'])
        data_diction['responses'].append(datum['responses'])
print('complete')    

complete


In [7]:
data_diction

{'tag': ['greeting',
  'greeting',
  'greeting',
  'greeting',
  'greeting',
  'goodbye',
  'goodbye',
  'goodbye',
  'thanks',
  'thanks',
  'thanks',
  'hours',
  'hours',
  'hours',
  'payments',
  'payments',
  'payments',
  'opentoday',
  'opentoday',
  'opentoday'],
 'patterns': ['Hi',
  'How are you',
  'Is anyone there?',
  'Hello',
  'Good day',
  'Bye',
  'See you later',
  'Goodbye',
  'Thanks',
  'Thank you',
  "That's helpful",
  'What hours are you open?',
  'What are your hours?',
  'When are you open?',
  'Do you take credit cards?',
  'Do you accept Mastercard?',
  'Are you cash only?',
  'Are you open today?',
  'When do you open today?',
  'What are your hours today?'],
 'responses': [['Hello, thanks for visiting',
   'Good to see you again',
   'Hi there, how can I help?'],
  ['Hello, thanks for visiting',
   'Good to see you again',
   'Hi there, how can I help?'],
  ['Hello, thanks for visiting',
   'Good to see you again',
   'Hi there, how can I help?'],
  ['Hel

In [8]:
dataset = pd.DataFrame(data_diction)
dataset

tag                    patterns  \
0    greeting                          Hi   
1    greeting                 How are you   
2    greeting            Is anyone there?   
3    greeting                       Hello   
4    greeting                    Good day   
5     goodbye                         Bye   
6     goodbye               See you later   
7     goodbye                     Goodbye   
8      thanks                      Thanks   
9      thanks                   Thank you   
10     thanks              That's helpful   
11      hours    What hours are you open?   
12      hours        What are your hours?   
13      hours          When are you open?   
14   payments   Do you take credit cards?   
15   payments   Do you accept Mastercard?   
16   payments          Are you cash only?   
17  opentoday         Are you open today?   
18  opentoday     When do you open today?   
19  opentoday  What are your hours today?   

                                            responses  
0   [Hello, thanks for visiting, Good to see you a...  
1   [Hello, thanks for visiting, Good to see you a...  
2   [Hello, thanks for visiting, Good to see you a...  
3   [Hello, thanks for visiting, Good to see you a...  
4   [Hello, thanks for visiting, Good to see you a...  
5   [See you later, thanks for visiting, Have a ni...  
6   [See you later, thanks for visiting, Have a ni...  
7   [See you later, thanks for visiting, Have a ni...  
8            [Happy to help!, Any time!, My pleasure]  
9            [Happy to help!, Any time!, My pleasure]  
10           [Happy to help!, Any time!, My pleasure]  
11  [We're open every day 9am-9pm, Our hours are 9...  
12  [We're open every day 9am-9pm, Our hours are 9...  
13  [We're open every day 9am-9pm, Our hours are 9...  
14  [We accept VISA, Mastercard and AMEX, We accep...  
15  [We accept VISA, Mastercard and AMEX, We accep...  
16  [We accept VISA, Mastercard and AMEX, We accep...  
17  [We're open every day from 9am-9pm, Our hours ...  
18  [We're open every day from 9am-9pm, Our hours ...  
19  [We're open every day from 9am-9pm, Our hours ...

In [9]:
dataset.shape

(20, 3)

In [10]:
sample = ' '.join(dataset['responses'][0])
sample

'Hello, thanks for visiting Good to see you again Hi there, how can I help?'

In [11]:
import string 
stemmer = PorterStemmer()
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from tqdm.notebook import tqdm
from sklearn.preprocessing import LabelEncoder

In [12]:
# remove punctuation, and stem... basic procesing

In [13]:
string.punctuation
''.join([stemmer.stem(samp) for samp in sample if not samp in string.punctuation])

'hello thanks for visiting good to see you again hi there how can i help'

In [14]:
# peform operation on all patterns
def clean_data(texts):
    # texts = ' '.join(texts)
    return ''.join([stemmer.stem(text) for text in texts if not text in string.punctuation])

tqdm.pandas()

# apply cleaning operation
dataset['clean_patterns'] =  dataset['patterns'].progress_apply(lambda x: clean_data(x))

dataset.head()

  0%|          | 0/20 [00:00<?, ?it/s]

tag          patterns  \
0  greeting                Hi   
1  greeting       How are you   
2  greeting  Is anyone there?   
3  greeting             Hello   
4  greeting          Good day   

                                           responses   clean_patterns  
0  [Hello, thanks for visiting, Good to see you a...               hi  
1  [Hello, thanks for visiting, Good to see you a...      how are you  
2  [Hello, thanks for visiting, Good to see you a...  is anyone there  
3  [Hello, thanks for visiting, Good to see you a...            hello  
4  [Hello, thanks for visiting, Good to see you a...         good day

In [15]:
dataset.clean_patterns.to_list()

['hi',
 'how are you',
 'is anyone there',
 'hello',
 'good day',
 'bye',
 'see you later',
 'goodbye',
 'thanks',
 'thank you',
 'thats helpful',
 'what hours are you open',
 'what are your hours',
 'when are you open',
 'do you take credit cards',
 'do you accept mastercard',
 'are you cash only',
 'are you open today',
 'when do you open today',
 'what are your hours today']

In [16]:
# vectorizaing operation
cv = CountVectorizer()
vectors = cv.fit_transform(dataset.clean_patterns)
vectors

<20x32 sparse matrix of type '<class 'numpy.int64'>'
	with 60 stored elements in Compressed Sparse Row format>

In [17]:
cv.vocabulary_

{'hi': 13,
 'how': 15,
 'are': 2,
 'you': 30,
 'is': 16,
 'anyone': 1,
 'there': 26,
 'hello': 11,
 'good': 9,
 'day': 7,
 'bye': 3,
 'see': 21,
 'later': 17,
 'goodbye': 10,
 'thanks': 24,
 'thank': 23,
 'thats': 25,
 'helpful': 12,
 'what': 28,
 'hours': 14,
 'open': 20,
 'your': 31,
 'when': 29,
 'do': 8,
 'take': 22,
 'credit': 6,
 'cards': 4,
 'accept': 0,
 'mastercard': 18,
 'cash': 5,
 'only': 19,
 'today': 27}

In [18]:
x = vectors.toarray()
x

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0,

In [19]:
dataset.head()

tag          patterns  \
0  greeting                Hi   
1  greeting       How are you   
2  greeting  Is anyone there?   
3  greeting             Hello   
4  greeting          Good day   

                                           responses   clean_patterns  
0  [Hello, thanks for visiting, Good to see you a...               hi  
1  [Hello, thanks for visiting, Good to see you a...      how are you  
2  [Hello, thanks for visiting, Good to see you a...  is anyone there  
3  [Hello, thanks for visiting, Good to see you a...            hello  
4  [Hello, thanks for visiting, Good to see you a...         good day

In [20]:
dataset['tag'] = dataset.tag.astype('category')
dataset.head(3)

tag          patterns  \
0  greeting                Hi   
1  greeting       How are you   
2  greeting  Is anyone there?   

                                           responses   clean_patterns  
0  [Hello, thanks for visiting, Good to see you a...               hi  
1  [Hello, thanks for visiting, Good to see you a...      how are you  
2  [Hello, thanks for visiting, Good to see you a...  is anyone there

In [21]:
# print(dataset.tag.cat.codes)

In [22]:
dataset.tag.cat.categories

Index(['goodbye', 'greeting', 'hours', 'opentoday', 'payments', 'thanks'], dtype='object')

In [23]:
lbl_mapper = dict(enumerate(dataset.tag.cat.categories))
lbl_mapper

{0: 'goodbye',
 1: 'greeting',
 2: 'hours',
 3: 'opentoday',
 4: 'payments',
 5: 'thanks'}

In [24]:
y = dataset.tag.cat.codes
y

0     1
1     1
2     1
3     1
4     1
5     0
6     0
7     0
8     5
9     5
10    5
11    2
12    2
13    2
14    4
15    4
16    4
17    3
18    3
19    3
dtype: int8

In [25]:
# encode the output
lb = LabelEncoder()
tag_encode = lb.fit_transform(dataset.tag)
tag_encode

array([1, 1, 1, 1, 1, 0, 0, 0, 5, 5, 5, 2, 2, 2, 4, 4, 4, 3, 3, 3])

In [26]:
# label encoder can also be used

In [27]:
import joblib
joblib.dump(tag_encode, 'lbl_encode.jb')

['lbl_encode.jb']

In [28]:
x.shape

(20, 32)

In [29]:
import numpy as np
x_input = np.expand_dims(x, axis=0)
x_input

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
         1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        

In [30]:
output_size = len(y.unique())
output_size

6

In [31]:
x_input.shape

(1, 20, 32)

In [32]:
y.shape

(20,)

In [33]:
# training ... using ANN
import tensorflow as tf 
from tensorflow import keras

In [34]:
# input
input_d =  keras.Input(shape=(32, ), name='input')

# dense layer
d1 = keras.layers.Dense(128, activation='relu', name='d1')(input_d)
d2 = keras.layers.Dense(63, activation='relu', name='d2')(d1)

# ouput
output = keras.layers.Dense(output_size, activation='softmax', name='output')(d2)

# build the model 
bot_model = keras.models.Model(inputs=input_d, outputs=output)

# model compilation 
bot_model.compile(
    loss='sparse_categorical_crossentropy', 
    optimizer='adam',
    metrics=['accuracy']
)

bot_model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input (InputLayer)          [(None, 32)]              0         
                                                                 
 d1 (Dense)                  (None, 128)               4224      
                                                                 
 d2 (Dense)                  (None, 63)                8127      
                                                                 
 output (Dense)              (None, 6)                 384       
                                                                 
Total params: 12,735
Trainable params: 12,735
Non-trainable params: 0
_________________________________________________________________


In [35]:
y

0     1
1     1
2     1
3     1
4     1
5     0
6     0
7     0
8     5
9     5
10    5
11    2
12    2
13    2
14    4
15    4
16    4
17    3
18    3
19    3
dtype: int8

In [36]:
bot_model.fit(x=x, y=y, epochs=30)

Epoch 1/30
1/1 [==============================] - 4s 4s/step - loss: 1.8837 - accuracy: 0.0500
Epoch 2/30
1/1 [==============================] - 0s 37ms/step - loss: 1.8434 - accuracy: 0.1000
Epoch 3/30
1/1 [==============================] - 0s 17ms/step - loss: 1.8051 - accuracy: 0.1500
Epoch 4/30
1/1 [==============================] - 0s 35ms/step - loss: 1.7688 - accuracy: 0.2500
Epoch 5/30
1/1 [==============================] - 0s 42ms/step - loss: 1.7340 - accuracy: 0.3000
Epoch 6/30
1/1 [==============================] - 0s 22ms/step - loss: 1.7012 - accuracy: 0.3500
Epoch 7/30
1/1 [==============================] - 0s 39ms/step - loss: 1.6703 - accuracy: 0.4500
Epoch 8/30
1/1 [==============================] - 0s 40ms/step - loss: 1.6407 - accuracy: 0.5000
Epoch 9/30
1/1 [==============================] - 0s 30ms/step - loss: 1.6120 - accuracy: 0.5000
Epoch 10/30
1/1 [==============================] - 0s 43ms/step - loss: 1.5839 - accuracy: 0.5500
Epoch 11/30
1/1 [==============

In [37]:
import joblib
joblib.dump(bot_model, 'bot_model_v1.jb')

Keras weights file (<HDF5 file "variables.h5" (mode r+)>) saving:
...layers\dense
......vars
.........0
.........1
...layers\dense_1
......vars
.........0
.........1
...layers\dense_2
......vars
.........0
.........1
...layers\input_layer
......vars
...metrics\mean
......vars
.........0
.........1
...metrics\mean_metric_wrapper
......vars
.........0
.........1
...optimizer
......vars
.........0
.........1
.........10
.........11
.........12
.........2
.........3
.........4
.........5
.........6
.........7
.........8
.........9
...vars
Keras model archive saving:
File Name                                             Modified             Size
config.json                                    2024-08-08 18:41:16         2086
metadata.json                                  2024-08-08 18:41:16           64
variables.h5                                   2024-08-08 18:41:16       176496


['bot_model_v1.jb']

In [38]:
bot_m = joblib.load('bot_model_v1.jb')
# load model
# bot_model

Keras model archive loading:
File Name                                             Modified             Size
config.json                                    2024-08-08 18:41:16         2086
metadata.json                                  2024-08-08 18:41:16           64
variables.h5                                   2024-08-08 18:41:16       176496
Keras weights file (<HDF5 file "variables.h5" (mode r)>) loading:
...layers\dense
......vars
.........0
.........1
...layers\dense_1
......vars
.........0
.........1
...layers\dense_2
......vars
.........0
.........1
...layers\input_layer
......vars
...metrics\mean
......vars
.........0
.........1
...metrics\mean_metric_wrapper
......vars
.........0
.........1
...optimizer
......vars
.........0
.........1
.........10
.........11
.........12
.........2
.........3
.........4
.........5
.........6
.........7
.........8
.........9
...vars


In [39]:
# prompt
sample_text = 'what hours do you guys open'
# cv.transform(sample_text)

In [40]:
# clean
clean_input = clean_data(sample_text)
clean_input

'what hours do you guys open'

In [41]:
# vectorize 
input_vec = cv.transform([clean_input])
input_vec.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 1, 0]], dtype=int64)

In [42]:
# predict
prediction = bot_model.predict(input_vec)
prediction

1/1 [==============================] - 0s 484ms/step


array([[0.04402477, 0.0514805 , 0.40310618, 0.1712495 , 0.27230245,
        0.0578366 ]], dtype=float32)

In [43]:
# indexing prediction
predicted = [np.argmax(pre) for pre in prediction][0]
predicted

2

In [44]:
# getting the value for label mapper 
pre = lbl_mapper[predicted]
pre

'hours'

In [45]:
def get_response(dataset, pre): 
    response = dataset['responses'][dataset['tag'] == pre].tolist()[-1]
    return np.random.choice(response)

get_response(dataset, pre)

'Our hours are 9am-9pm every day'

In [51]:

# peform operation on all patterns
def clean_data(texts):
    # texts = ' '.join(texts)
    return ''.join([stemmer.stem(text) for text in texts if not text in string.punctuation])

def get_response(dataset, pre): 
    response = dataset['responses'][dataset['tag'] == pre].tolist()[-1]
    return np.random.choice(response)

# bot engine
def bot(text):
    clean_input = clean_data(text.lower())
    input_vec = cv.transform([clean_input])
    prediction = bot_model.predict(input_vec)
    predicted = [np.argmax(pre) for pre in prediction][0]
    print(predicted)
    pre = lbl_mapper[predicted]
    print(pre)
    response = get_response(dataset, pre)
    return response, pre

# goodbye
while True: 
    text = input('User:', )
    if text == '-1': 
        print('Bot: ', 'have a great day....' )
        break

    response, pre = bot(text)
    print('Bot: ', response )
    if pre=='goodbye':
        break
    

    

User: hello


1/1 [==============================] - 0s 77ms/step
1
greeting
Bot:  Good to see you again


User: how was today


1/1 [==============================] - 0s 75ms/step
3
opentoday
Bot:  Our hours are 9am-9pm every day


User: okk


1/1 [==============================] - 0s 31ms/step
5
thanks
Bot:  Happy to help!


User: what time do you open


1/1 [==============================] - 0s 45ms/step
2
hours
Bot:  Our hours are 9am-9pm every day


User: good


1/1 [==============================] - 0s 38ms/step
1
greeting
Bot:  Hi there, how can I help?


User: bye


1/1 [==============================] - 0s 40ms/step
0
goodbye
Bot:  Have a nice day


In [49]:
lbl_mapper

{0: 'goodbye',
 1: 'greeting',
 2: 'hours',
 3: 'opentoday',
 4: 'payments',
 5: 'thanks'}